services:
  - type: web
    name: coveda-internship
    runtime: node
    rootDir: level-1/rest-api
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: DATABASE_URL
        sync: false
